# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea81acf49c4d82fcd8356e98e39fb1cd152ceca2fbae54ba6d5fe0a74500e0f1a0c40b68a48e1769f2a8aca8614eb3e78c075c6696e0e8fc74dfa6adc9e9fb29

test:
  secret_key_base: acdac3622c404f5951c9bede685bc839aa5b3158333c9d594bf40e4fe2af55811041c54a4176afb0945fa5ac60b90db2ccc4b31e57cca87e1a8302361ecdd7bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
